//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genshin.Downloader {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genshin.Downloader.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新失败 的本地化字符串。
        /// </summary>
        public static string error_failedCheckUpdate {
            get {
                return ResourceManager.GetString("error.failedCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取版本信息 的本地化字符串。
        /// </summary>
        public static string error_failedGetVersion {
            get {
                return ResourceManager.GetString("error.failedGetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可用的预下载 的本地化字符串。
        /// </summary>
        public static string error_preDownloadNotFound {
            get {
                return ResourceManager.GetString("error.preDownloadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可下载的资源 的本地化字符串。
        /// </summary>
        public static string error_resourceNotFound {
            get {
                return ResourceManager.GetString("error.resourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有识别到游戏渠道，请手动选择！ 的本地化字符串。
        /// </summary>
        public static string mbox_channelNotFound {
            get {
                return ResourceManager.GetString("mbox.channelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制成功 的本地化字符串。
        /// </summary>
        public static string mbox_copyS {
            get {
                return ResourceManager.GetString("mbox.copyS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置游戏目录！ 的本地化字符串。
        /// </summary>
        public static string mbox_gamePathEmpty {
            get {
                return ResourceManager.GetString("mbox.gamePathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动失败，或许你没有安装好原神？ 的本地化字符串。
        /// </summary>
        public static string mbox_launchFailed {
            get {
                return ResourceManager.GetString("mbox.launchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有需要修复的文件！ 的本地化字符串。
        /// </summary>
        public static string mbox_nothing2Fix {
            get {
                return ResourceManager.GetString("mbox.nothing2Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string mbox_notice {
            get {
                return ResourceManager.GetString("mbox.notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定资源包或指定的资源包不存在 的本地化字符串。
        /// </summary>
        public static string mbox_packageEmpty {
            get {
                return ResourceManager.GetString("mbox.packageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意外的资源包类型 的本地化字符串。
        /// </summary>
        public static string mbox_packageTypeException {
            get {
                return ResourceManager.GetString("mbox.packageTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string mbox_saveF {
            get {
                return ResourceManager.GetString("mbox.saveF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string mbox_saveS {
            get {
                return ResourceManager.GetString("mbox.saveS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你选择的资源包版本 ({0})\r\n可能不适用于已安装的游戏版本 ({1})\r\n是否仍要使用该资源包？ 的本地化字符串。
        /// </summary>
        public static string mbox_versionException {
            get {
                return ResourceManager.GetString("mbox.versionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在删除文件.. 的本地化字符串。
        /// </summary>
        public static string msg_doing_delete {
            get {
                return ResourceManager.GetString("msg.doing.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在执行 HPatch.. 的本地化字符串。
        /// </summary>
        public static string msg_doing_hpatch {
            get {
                return ResourceManager.GetString("msg.doing.hpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在应用更新.. 的本地化字符串。
        /// </summary>
        public static string msg_doing_update {
            get {
                return ResourceManager.GetString("msg.doing.update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到该游戏渠道的 API 的本地化字符串。
        /// </summary>
        public static string msg_error_notfound {
            get {
                return ResourceManager.GetString("msg.error.notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误代码： 的本地化字符串。
        /// </summary>
        public static string msg_failed_code {
            get {
                return ResourceManager.GetString("msg.failed.code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务未正常完成 的本地化字符串。
        /// </summary>
        public static string msg_failed_task {
            get {
                return ResourceManager.GetString("msg.failed.task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [执行中] 正在检查更新.. 的本地化字符串。
        /// </summary>
        public static string tbox_checkingUpdate {
            get {
                return ResourceManager.GetString("tbox.checkingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        public static string tbox_error {
            get {
                return ResourceManager.GetString("tbox.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新版本可下载 的本地化字符串。
        /// </summary>
        public static string tbox_newFound {
            get {
                return ResourceManager.GetString("tbox.newFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已是最新版本，若资源缺失可尝试修复器 的本地化字符串。
        /// </summary>
        public static string tbox_updated {
            get {
                return ResourceManager.GetString("tbox.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待服务器响应 的本地化字符串。
        /// </summary>
        public static string tbox_waitServer {
            get {
                return ResourceManager.GetString("tbox.waitServer", resourceCulture);
            }
        }
    }
}
