name: .NET Core Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.7
      
    - name: Build
      run: dotnet publish -p:PublishProfile=FolderProfile -p:EnableWindowsTargeting=true
      
    - name: Zip the Build
      run: zip -j -r Genshin.Downloader.zip ./bin/publish/
      
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Genshin.Downloader.zip
