name: .NET Core Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
      
    - name: Build
      run: dotnet publish -p:PublishProfile=FolderProfile -p:EnableWindowsTargeting=true
      
    - name: 7-Zip the Build
      run: 7za a Genshin.Downloader.7z ./bin/publish/* -mx=9
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Genshin.Downloader.7z
